### ISSUE TITLE
IntelliJ 14: push to Gerrit invokes direct push (when multiple repositories are available in one project)

### ISSUE THREAD

**Issue by ihorpts** [uwolfer/gerrit-intellij-plugin#139]
Hello

When I'm trying to push to Gerrit my changes they actually pushed directly to the git repo, for more details see attached screenshot below:

![direct push](https://cloud.githubusercontent.com/assets/7080319/5316815/45b8b2ca-7c90-11e4-91af-c460f06d584c.jpg)

**Comment by bond-** [comment]
:+1:  to this issue I just got burned today :(

Is there a bug created on IntelliJ tracker? Kindly share the link.

**Comment by bond-** [comment]
Vote for the issue: https://youtrack.jetbrains.com/issue/IDEA-98878

**Comment by ihorpts** [comment]
@bond- thx!

**Comment by yairogen** [comment]
For multi repository support why not run:
git remote show origin
and parse the response and that way you "know" the right repository? also for branches I find it that you can edit the refs/for part manually in the push dialog. isn't that enough?

**Comment by EnlightningMan** [comment]
Hi.

I've tried your plugin and really liked it with a single test branch. Unfortunately, I just ran into the same problem as described here when trying to set up Gerrit with the current versions of WebStorm and PhpStorm.


Regarding your question about the workflow:

We also have multiple repositories and our workflow normally is:
1. We create a branch in all the synced repositories at the same time (because that way it is easier to switch branches in IntelliJ).
2. We do our changes which affect multiple repositories at the same time (multiple client-projects using a shared engine)
3. We commit and use the IntelliJ push dialog pushing these changes to a branch with the same name in all repositories at once.

I would be perfectly fine with me if selecting a different branch in the "Push to Gerrit" settings would result in pushing to that branch / creating that branch in all selected repositories.

Otherwise, disabling the "push to a different" branch functionality of the plugin and making me change it by hand in the list would also be ok.


Like it is now, it doesn't work at all in the current version, which is why I will not continue trying to set up Gerrit right now... It would actually have helped, if the plugin page would say something about that limitation, it would have saved me a day or two of trying to understand how the gerrit system can be set up and figuring out why it ignores my push deny settings ;)
If you can't fix it, I'll just have to wait for Jetbrains' Upsource IDE integration.

**Comment by uwolfer** [comment]
@EnlightningMan: Thanks for your feedback.

I will try to improve this situation. I'm also in contact with Jetbrain developers in order to extend the push dialog API which should allow better integrastion for plugins. I will post any updates here.

**Comment by igreenfield** [comment]
I also need this feature.

**Comment by vintagedance** [comment]
I just upgraded from IntelliJ 13 to IntelliJ 14 and am now getting bitten by this bug as well.  It looks just like the picture that @ihorpts posted.

**Comment by vintagedance** [comment]
Suggestion:  In the short term, for multi repository projects, default to NO repositories selected.  Then only allow a single repository to be checked and just push to that one.

Stage 2 would be similar to what EnlightningMan suggests:  Only support multi-repository if they are all going to the same branch/feature.

But I understand that there may be some underlying bugs or deficiencies in the new IntelliJ 14 API to permit this.  I followed the link above to the youtrack system, but it wasn't clear to me which bugs were directly related and critical to fix for the gerrit plugin to work properly.

Not sure if another possibility would be to have developers manually set the refspec from the git command line  master:refs/for/master?  Or if one of the other bugs is that IntelliJ won't honor that either?

**Comment by uwolfer** [comment]
You can find (and vote for) my request for extending the push dialog plugin API here:
https://youtrack.jetbrains.com/issue/IDEA-136937

Nevertheless I'll try to get the best possible done for multi-repo-projects before this is available in IntelliJ.

**Comment by uwolfer** [comment]
Good news!

I hope everyone is happy with the multi-repo-push-dialog I have implemented.

Please test it (IntelliJ 14 only build (does not work with 14.1 EAP; I will release an update soon)): http://urswolfer.com/gerrit-intellij-plugin/testbuilds/20150227/gerrit-intellij-plugin-14.zip

**Comment by uwolfer** [comment]
Updated test-build (please see comment above): http://urswolfer.com/gerrit-intellij-plugin/testbuilds/20150304/gerrit-intellij-plugin-14.zip
