### ISSUE TITLE
All interactions returning "Unexpectedly empty response" - IntelliJ 2017.1.3

### ISSUE THREAD

**Issue by david-hatton** [uwolfer/gerrit-intellij-plugin#278]
Any interaction with the gerrit plugin which requires sending changes to the gerrit server results in::

com.google.gerrit.extensions.restapi.RestApiException: Unexpectedly empty response

E.g. Failed set file review status for Gerrit change, Failed to save draft comment.

Read only operations work fine, viewing reviews, diffs, etc.

The version of the gerrit server is 2.12.5-81-g2b96d11. 

The version of the gerrit plugin is 0.9.9.1-146

**Comment by uwolfer** [comment]
Is your Gerrit instance public? So I could test against it.

If not, please try to access http://your-gerrit.example.com/a/changes/ in a webbrowser. Does that work?

**Comment by david-hatton** [comment]
Our gerrit instance is not public.

I am no sure exactly what you mean ... but for example the URL for the gerrit review which was causing problems was:

https://gerrit.url/#/c/2379034/2

I tried to open

http://gerrit.url/#/c/2379034/2/a/changes
http://gerrit.url/#/c/2379034/a/changes
http://gerrit.url/#/c/a/changes
http://gerrit.url/#/a/changes
http://gerrit.url/a/changes

none of these work.

**Comment by uwolfer** [comment]
Please add a trailing slash to the last URL (http://gerrit.url/a/changes/). That should return a JSON response. If that does not work, REST access to your Gerrit instance seems to restricted / does not work. Please contact your administrator in that case.

See also: https://gerrit-review.googlesource.com/Documentation/rest-api.html

**Comment by david-hatton** [comment]
I got the JSON response. from that URL.

FYI: 

1. I previously had the gerrit plugin working - with older version of IJ and (possibly) older version of plugin.
2. Read Only operations work fine ... e.g. I can view reviews, view diffs of files ... but anything which causes a write to the gerrit server is failing. See attached snapshots.

![gerrit1a](https://cloud.githubusercontent.com/assets/8503948/26445401/098a9bf0-4138-11e7-98f5-1b36e93de909.png)

![gerrit2](https://cloud.githubusercontent.com/assets/8503948/26445694/ce064dd0-4138-11e7-8043-baa3b8098f3d.png)

**Comment by uwolfer** [comment]
Ah, okay. I missed that part in your initial report - sorry.

So it looks like there is an authentication issue.

When you open IntelliJ Gerrit plugin settings, are there values in the fields password and username?

Probably you could also check if that hint works for you:
https://github.com/uwolfer/gerrit-intellij-plugin/issues/277#issuecomment-302640386

**Comment by david-hatton** [comment]
I do have credentials set. I also tried setting HTML password. It still connects .. but I am getting the same error.

**Comment by uwolfer** [comment]
What happens when you right-click a change and click action "Star"?

**Comment by david-hatton** [comment]
Failed to star Gerrit change.
Not supported for Gerrit instances older than version 2.8.
com.google.gerrit.extensions.restapi.RestApiException: Unexpectedly empty response.

**Comment by uwolfer** [comment]
Do you know if anything on your Gerrit server setup has changed since the last time you used it with success?

It's really strange that this exception gets thrown. When I debug the "Star" action, the method returns here:
https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L136

In your case, line 143 is hit: https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L143

But at least for adding a new file comment, it should return at line 146:
https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L145

Your server seems to return the same response in any case... Can you please check if the star is saved when you access the web UI? If it is not, your Gerrit server returns a wrong HTTP status (it should return a failed code like 403, which is handled here: https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/GerritRestClient.java#L227).

How do you authenticate in the web UI? HTTP credentials or some single sign on solution?

**Comment by uwolfer** [comment]
@david-hatton: Can you still reproduce this issue? If yes, please see my questions above.

**Comment by david-hatton** [comment]
> Do you know if anything on your Gerrit server setup has changed since the last time you used it with success?

It changed from version 2.11 to version 2.12.5 in October 2016. It is possible that the last time I had this working was pre-October. I cannot remember to be honest. 

> Can you please check if the star is saved when you access the web UI?

The star is not saved.

> How do you authenticate in the web UI? HTTP credentials or some single sign on solution?

On the Web UI we use a single sign on. However I have set the HTTP password as per your advice earlier and that is the password I use in the Gerrit Plugin.

**Comment by david-hatton** [comment]
Hi,

FYI this issue has disappeared .. I am not sure what the factor was but two things happened more or less at the same time: I upgraded IJ 2018.3 to and the gerrit server upgraded to 2.14.16.

Either way .. I am happy that the problem is gone..

**Comment by david-hatton** [comment]
Hi,

This issue has re-appeared. Would you like a new ticket opened or can this be re-used.

The situation is broadly the same.

My current setup is:

IJ: 222.3739.24
Plugin: 1.2.6-203
Server: 2.14.22
