### ISSUE TITLE
Can no longer use multiple instances

### ISSUE THREAD

**Issue by charlieejn** [uwolfer/gerrit-intellij-plugin#286]
I updated my plugin to 1.0.1-146 on Macbook Pro running Sierra and I was unable to use multiple Gerrit instances in multiple open Android Studio projects. I usually have two projects open in separate windows, and I review Gerrit separately for each repo. After the upgrade, as soon as I openedthe second window it greyed out Gerrit on the first window and only let me review the second one.

I've rolled back to 1.0.0.1 and it's working again.

**Comment by uwolfer** [comment]
Thanks for your report. This is broken because of the following change: https://github.com/uwolfer/gerrit-intellij-plugin/commit/40189fa7745717be668b413f0a34c595451cb044

I have asked in the IntelliJ plugin forum how to resolve this issue in a clean way:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000534584-Access-toolwindow-from-an-action
