### ISSUE TITLE
Cannot Login to Gerrit Server

### ISSUE THREAD

**Issue by abihani10** [uwolfer/gerrit-intellij-plugin#321]
Hello,

I am using intellij 2018.1 ultimate edition.
Just wanted to know which plugin is compatible with this intellij edition.

I tried using the one from https://plugins.jetbrains.com/plugin/7272-gerrit. (downloaded the latest one)
But its not working at the very first step. I am not able to login to our gerrit Server.
I get error as below on Test connection

com.google.gerrit.extensions.restapi.RestApiException: Request failed.

Could you please help here?

P.S. - Gerrit server version is 2.14

Thanks in advanced.

**Comment by uwolfer** [comment]
@abihani10: Can you please post the URL you are using (feel free to anonymize the domain name)? The plugin is compatible with this version of IntelliJ and Gerrit.

**Comment by abihani10** [comment]
@uwolfer - we are using this URL: http://abcgerrit:8080

**Comment by uwolfer** [comment]
@abihani10: Thanks. I assume this is the URL you are also using when you access Gerrit with your web browser (also check if you are using HTTP / HTTPS)? Please verify that you are using exactly the same URL as you are using in the the browser. Please also note the password hint in the connection dialog.

Also, I suggest downloading the plugin in IntelliJ settings -> plugins in order to get updates, but I think this does not fix your current issue.

**Comment by abihani10** [comment]
@uwolfer Thanks for the suggestions. I had implemented all of those before asking the question here.
But out of nowhere when I tried to test the connection today morning, unbelievably it worked.

Have no idea what went wrong and what is right now.
Anyways that solved my issue. Thanks for the prompt help!! :)
