### ISSUE TITLE
Can't use IDE without loggining into gerrit

### ISSUE THREAD

**Issue by dmitvitalii** [uwolfer/gerrit-intellij-plugin#325]
I can't use my IDE because of the **"Gerrit Password"** dialog.
Since the plugin is not able to connect to gerrit in my case, I can't just cancel the dialog: there is a button, but a dialog appears again and again.

![image](https://user-images.githubusercontent.com/14320898/45405512-d66ca380-b66b-11e8-900e-4f887506ea11.png)

I had to remove it from `~/.IdeaIC2018.1/config/plugins/` to be able to work.

**Comment by uwolfer** [comment]
@dmitvitalii: Did it appear again right after clicking "cancel" or was there a delay between the next appearance of the dialog?

Did the dialog show up right after starting the IDE?

**Comment by dmitvitalii** [comment]
> Did it appear again right after clicking "cancel" or was there a delay between the next appearance of the dialog?

It appears immediately after clicking the button with no delay.

> Did the dialog show up right after starting the IDE?

Yes.
I've installed the plugin, added gerrit configurations (link, username, pass), pressed the refresh button in a bottom window. Got an error message "Unable to connect" (or something like that), rebooted with no issues. Worked without logging just fine.

Then I've finished my work and closed IDEA.
Next day I launch the IDE and this issue happens.

**Comment by uwolfer** [comment]
@dmitvitalii: I've tried to reproduce your issue. Was able to reproduce parts of it: When I setup Gerrit plugin with an URL and username, but without specifying a password, the dialog open two times when I press the "Refresh" button in the list. After closing the dialog two times, it does not show up anymore. The same happens when I disable the password safe in IntelliJ and restart it. This might be what you do? Could you tell me what your "Passwords" settings in IntelliJ have set? I use the option "In KeePass".

Does the dialog also appear again when you use the window manager "X" button?

**Comment by dmitvitalii** [comment]
Unfortunately, I'm unable to tell this since I've removed the plugin, but I didn't change default settings and I didn't use KeePass for that.
