### ISSUE TITLE
Support  Gerrit 2.15 flags

### ISSUE THREAD

**Issue by mdindoffer** [uwolfer/gerrit-intellij-plugin#334]
Gerrit 2.15 removed the "`drafts`" workflow. Instead users use the `%wip` and `%private` flags to set the WIP and private statuses on changes.
The plugin offers only the "Draft" checkbox in the push dialog, which obviously fails to push on Gerrit 2.15 and newer.
Please either add a checkbox for WIP and Private flags, or at least use the `%wip` as a fallback if push to `refs/drafts/*` fails.

**Comment by uwolfer** [comment]
Adding %private should be easy, but adding %wip which replaces drafts is not that easy in order to not clutter the push UI. I do not see any other possibility as adding a 2nd checkbox which tells the user that it is only supported for Gerrit 2.15+. (The IntelliJ push dialog does not provide any API for plugins, so it's really hard to extend it. Feel free to vote for this feature request: https://youtrack.jetbrains.com/issue/IDEA-136937)

**Comment by mdindoffer** [comment]
Can't we simply obtain the Gerrit server version via a REST call, inject it via [GerritPushExtensionPanel](https://github.com/uwolfer/gerrit-intellij-plugin/blob/21c92b889f9f3a378ccbc01a1fd673e120901870/src/main/java/com/urswolfer/intellij/plugin/gerrit/push/GerritPushExtensionPanel.java#L158) constructor and then either create a Draft or a WIP checkbox if version>=2.15 ?

**Comment by uwolfer** [comment]
I've not looked into it, but I think it's not that easy because the push dialog impl is really ugly because of the missing API: it's hacked into Intellij via reflection. So we need to modify classes very early before any push dialog related class is loaded. Requesting the server version requires user credentials for the REST request (at least in some Gerrit setups), which will most probably be too late.

**Comment by mdindoffer** [comment]
Hi, would it be possible to make a release? Or are there any snapshot builds available to try this?
Thanks

**Comment by uwolfer** [comment]
@mdindoffer: I have just pushed a new release.
